version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: moneycontrol-backend-container
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moneycontrol-frontend-container
    ports:
      - "4173:4173"
    depends_on:
      - backend
